name: flutter_pocket_plan_proyecto
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  uuid: ^4.5.1
  provider: ^6.1.5
  flutter_dotenv: ^5.2.1
  http: ^1.4.0
  fl_chart: ^0.63.0
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  pdf: ^3.10.7
  printing: ^5.11.0
  timezone: ^0.10.1
  flutter_local_notifications: ^19.2.1
  share_plus: ^11.0.0
  file_picker: ^10.1.9



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1  # Dependencia agregada aquí

flutter:
  uses-material-design: true
  assets:
    - assets/img/pocketplan.png  # Cambiado a pocketplan.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/img/pocketplan.png"  # Nombre exacto del archivo
  adaptive_icon_background: "#6A11CB"